### ISSUE TITLE
Compiler version incompatibility

### ISSUE THREAD

**Issue by McPringle** [JetBrains/kotlin-workshop#12]
# Steps to reproduce
1. clone the project: `git clone git@github.com:JetBrains/kotlin-workshop.git`
2. cd into the source directory: `cd kotlin-workshop/student/single`
3. run gradle build: `./gradlew assemble`

# Error message
```
:compileKotlin
e: java.lang.IllegalStateException: The provided plugin org.jetbrains.kotlin.scripting.compiler.plugin.ScriptingCompilerConfigurationComponentRegistrar is not compatible with this version of compiler
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:188)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:120)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:433)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:295)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:147)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:95)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:50)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:88)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:454)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:224)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:36)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:86)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.execIncrementalCompiler(CompileServiceImpl.kt:545)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.access$execIncrementalCompiler(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:418)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:927)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
        at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:957)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:926)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:417)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:835)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: org.jetbrains.kotlin.scripting.compiler.plugin.ScriptingCompilerConfigurationComponentRegistrar.registerProjectComponents(Lorg/jetbrains/kotlin/com/intellij/mock/MockProject;Lorg/jetbrains/kotlin/config/CompilerConfiguration;)V
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:186)
        ... 41 more

:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.442 secs
```

# Java Version
Java 8.0.172-zulu on macOS High Sierra 10.13.5

**Comment by devSC** [comment]
me too.

**Comment by devSC** [comment]
@McPringle i solved by update the version of kotlin plugin

**Comment by McPringle** [comment]
@devSC The Kotlin plugin for Gradle? The version mentioned in the build file (1.2.50) is the latest one. Which version are you using?

**Comment by dcn01** [comment]
me too.In android studio,build failed with this message.Any suggestions?

**Comment by madorb** [comment]
1.2.50 is failing for me as well

**Comment by armarti** [comment]
Upgrading to the unreleased Kotlin 1.2.51 worked for me (with tradeoffs): [link](https://discuss.kotlinlang.org/t/kotlin-1-2-50-causing-java-lang-illegalstateexception-scriptingcompilerconfigurationcomponentregistrar-is-not-compatible-with-this-version-of-compiler/8157/12?u=dcmorse)

**Comment by nasahapps** [comment]
Not for me, still failing with same error on 1.2.51 (which was just released to the stable channel this morning)

Gradle: 4.8.1
Kotlin: 1.2.51
Java: 8.0.161 on macOS 10.13.5

**Comment by armarti** [comment]
Actually I got the error again about an hour after I posted this. Then I switched the Gradle version to 4.7 and it works again.

**Comment by debop** [comment]
Still I got error again all cases ...

Gradle : 4.7, 4.8.1
Kotlin 1.2.50, 1.2.51   use sdk (sdkmin.io)
Java : 1.8_171 on Linux Mint 18.3

Just use Kotlin 1.2.41 is success.

**Comment by AndersonSantos-CL** [comment]
hey Guys, are you still facing this issue?

Well, I have the same, but I use spring-boot together, this issue is related to spring-boot I believe.

I just upgraded my kotlin to 1.2.51 and it is working but when I upgrade my spring-boot to anything above 1.5.14.RELEASE, this issue appears again.

my IDE plugin is up to date.

**Comment by McPringle** [comment]
@AndersonSantos-CL: Yes, I have still the same issues when I use Kotlin 1.2.50 and 1.2.51. If I use Kotlin 1.2.40, the build is successful.

**Comment by AndersonSantos-CL** [comment]
hey @McPringle, note that I am using 1.2.51 but cant upgrade mine spring-boot to latest version.

`buildscript {
    ext.kotlin_version = '1.2.51'
    ext.spring_boot_version = '1.5.14.RELEASE'

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:$spring_boot_version"
        classpath "org.jetbrains.kotlin:kotlin-noarg:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
        classpath 'org.liquibase:liquibase-core:3.5.5'
        classpath "org.liquibase:liquibase-gradle-plugin:1.1.1"
        classpath 'mysql:mysql-connector-java:5.1.13'
    }
}`
I really dont understand why.

BTW I am using IntelliJ and bundled Gradle.

**Comment by Somiona** [comment]
me too. the same error pops up after i upgraded to kotlin 1.2.51
`
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
   ext.kotlin_version = '1.2.51'

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
`
I'm using jdk10 gradle 4.9 and kotlin 1.2.51

**Comment by grahamiancummins** [comment]
Same issue. 
I am not using spring boot. 
Downgrading Kotlin to 1.2.41 resolves the issue consistently. 
Changing versions of other components, changing Gradle versions, or switching back and forth between Idea and Gradle builds, will sometimes fix the issue temporarily, but it returns. I think this effect must be related to cached build state.

EDIT:
The following does solve the issue for me, while still using kotlin 1.2.51:
Remove SDKMAN (rm -r ~/.sdkman, remove the reference to it from my .bashrc)
Remove ~/.gradle
Install openjdk-8 
Log in again
Build (with gradlew)

**Comment by jkwuc89** [comment]
The related Kotlin issue is below:
https://youtrack.jetbrains.com/issue/KT-24946

It is listed as fixed with a target version for the fix being 1.2.60. In the meantime, continue to use 1.2.41.

**Comment by jkwuc89** [comment]
After upgrading my Kotlin project to 1.2.60, I verified that this version does indeed fix this bug.

**Comment by HereThereBeMonsters** [comment]
Same problem with Kotlin 1.2.70 (installed via sdkman), and Android studio with Kotlin plugin v 1.2.70-studio. Then I opened the project in IntelliJ 18.2, upgraded the Kotlin plugin to 1.2.70, and it works. Not sure what the difference is.

**Comment by ajkueterman** [comment]
I'm seeing this same issue in 1.3.50 when using `classpath 'com.android.tools.lint:lint-gradle:26.5.0'`, but after removing lint-gradle from the classpath the problem resolved itself.

**Comment by PPTing** [comment]
> I'm seeing this same issue in 1.3.50 when using `classpath 'com.android.tools.lint:lint-gradle:26.5.0'`, but after removing lint-gradle from the classpath the problem resolved itself.

I meet it too but I must to implementation lint-gradle so cannot fix it

**Comment by vivekwolf123** [comment]
I m using kotlin version 1.3.61 and gradle version 4.0.0-alpha09 which seem to be the latest at the moment. Still the same issue.

**Comment by ghost** [comment]
I am upgraded to letest same issue
